from pathlib import Path
p=Path('src/App.jsx')
s=p.read_text(encoding='utf-8')
old="""    const shareApp = async () => {\n      const url = 'https://play.google.com/store/apps/details?id=com.randis2288.dartscorepro';\n      const payload = { title: 'DartScore Pro', text: t(lang, 'shareText'), url };\n      try {\n        if (navigator.share) {\n          await navigator.share(payload);\n          return;\n        }\n        if (navigator.clipboard?.writeText) {\n          await navigator.clipboard.writeText(url);\n          showToast(t(lang, 'linkCopied'));\n          return;\n        }\n        window.prompt(t(lang, 'shareApp'), url);\n      } catch (e) {\n        if (e?.name === 'AbortError') return;\n        try {\n          await navigator.clipboard?.writeText?.(url);\n          showToast(t(lang, 'linkCopied'));\n        } catch {\n          window.prompt(t(lang, 'shareApp'), url);\n        }\n      }\n    };\n"""
new="""    const shareApp = async () => {\n      const url = 'https://play.google.com/store/apps/details?id=com.randis2288.dartscorepro';\n      const payload = { title: 'DartScore Pro', text: t(lang, 'shareText'), url };\n      try {\n        if (window.DartScoreAndroid?.shareApp) {\n          window.DartScoreAndroid.shareApp(payload.title, payload.text, payload.url);\n          return;\n        }\n        if (navigator.share) {\n          await navigator.share(payload);\n          return;\n        }\n        if (navigator.clipboard?.writeText) {\n          await navigator.clipboard.writeText(url);\n          showToast(t(lang, 'linkCopied'));\n          return;\n        }\n        window.prompt(t(lang, 'shareApp'), url);\n      } catch (e) {\n        if (e?.name === 'AbortError') return;\n        try {\n          await navigator.clipboard?.writeText?.(url);\n          showToast(t(lang, 'linkCopied'));\n        } catch {\n          window.prompt(t(lang, 'shareApp'), url);\n        }\n      }\n    };\n"""
if old not in s:
    raise SystemExit('shareApp anchor not found')
p.write_text(s.replace(old,new,1),encoding='utf-8')
print('web native share bridge patch applied')
