from pathlib import Path

p=Path('src/App.jsx')
s=p.read_text(encoding='utf-8')
old="    const L = (cs, en) => lang === 'cs' ? cs : en;"
if old not in s:
    raise SystemExit('anchor missing')

new="""    const STATS_I18N = {
      cs:{statistics:'Statistiky',noSaved:'Zatím nejsou odehrané žádné uložené zápasy.',overview:'Přehled',h2h:'Vzájemné zápasy',all:'Vše',week:'Týden',month:'Měsíc',year:'Rok',avg3:'Průměr / 3 šipky',first9:'Prvních 9',checkoutPct:'Checkout %',checkoutPending:'Přesná evidence pokusů bude doplněna',highestCheckout:'Nejvyšší checkout',scoring:'Náhozy',performance:'Výkony',bestLeg:'Nejlepší leg (šipky)',avgDartsLeg:'Průměr šipek / leg',highestScore:'Nejvyšší nához',winRate:'Úspěšnost výher',matches:'vzájemných zápasů',legs:'Legy',sets:'Sety',last5:'Forma posledních 5',avgTrend:'Trend průměru',matchHistory:'Historie vzájemných zápasů',won:'vyhrál',checkout:'Checkout',detailed:({detailed,total})=>`Detailní metriky jsou dostupné u ${detailed} z ${total} zápasů. Starší zápasy zůstávají započítané do výher.`,older:'Starší zápasy jsou započítané do H2H skóre a úspěšnosti výher. Detailní metriky se plní jen u nově uložených zápasů.'},
      en:{statistics:'Statistics',noSaved:'No saved matches yet.',overview:'Overview',h2h:'Head-to-Head',all:'All',week:'Week',month:'Month',year:'Year',avg3:'3-dart AVG',first9:'First 9',checkoutPct:'Checkout %',checkoutPending:'Exact attempt tracking pending',highestCheckout:'Highest checkout',scoring:'Scoring',performance:'Performance',bestLeg:'Best leg (darts)',avgDartsLeg:'Avg darts / leg',highestScore:'Highest score',winRate:'Win rate',matches:'matches',legs:'Legs',sets:'Sets',last5:'Last 5 form',avgTrend:'AVG trend',matchHistory:'Match history',won:'won',checkout:'Checkout',detailed:({detailed,total})=>`Detailed metrics are available for ${detailed} of ${total} matches. Older matches still count toward wins.`,older:'Older matches count toward H2H score and win rate. Detailed metrics populate for newly saved matches.'},
      de:{statistics:'Statistiken',noSaved:'Noch keine gespeicherten Spiele.',overview:'Übersicht',h2h:'Direkte Duelle',all:'Alle',week:'Woche',month:'Monat',year:'Jahr',avg3:'3-Dart-Schnitt',first9:'Erste 9',checkoutPct:'Checkout %',checkoutPending:'Exakte Versuchsstatistik folgt',highestCheckout:'Höchstes Checkout',scoring:'Scoring',performance:'Leistung',bestLeg:'Bestes Leg (Darts)',avgDartsLeg:'Ø Darts / Leg',highestScore:'Höchster Score',winRate:'Siegquote',matches:'direkte Duelle',legs:'Legs',sets:'Sätze',last5:'Form letzte 5',avgTrend:'AVG-Trend',matchHistory:'Duell-Historie',won:'gewann',checkout:'Checkout',detailed:({detailed,total})=>`Detaillierte Werte sind für ${detailed} von ${total} Spielen verfügbar. Ältere Spiele zählen weiter für Siege.`,older:'Ältere Spiele zählen für H2H und Siegquote. Detailwerte werden nur bei neu gespeicherten Spielen erfasst.'},
      es:{statistics:'Estadísticas',noSaved:'Aún no hay partidas guardadas.',overview:'Resumen',h2h:'Cara a cara',all:'Todo',week:'Semana',month:'Mes',year:'Año',avg3:'Promedio / 3 dardos',first9:'Primeros 9',checkoutPct:'Checkout %',checkoutPending:'El registro exacto de intentos se añadirá',highestCheckout:'Checkout más alto',scoring:'Puntuación',performance:'Rendimiento',bestLeg:'Mejor leg (dardos)',avgDartsLeg:'Prom. dardos / leg',highestScore:'Puntuación más alta',winRate:'Porcentaje de victorias',matches:'enfrentamientos',legs:'Legs',sets:'Sets',last5:'Forma últimos 5',avgTrend:'Tendencia AVG',matchHistory:'Historial de enfrentamientos',won:'ganó',checkout:'Checkout',detailed:({detailed,total})=>`Las métricas detalladas están disponibles en ${detailed} de ${total} partidas. Las anteriores siguen contando para las victorias.`,older:'Las partidas anteriores cuentan para el H2H y el porcentaje de victorias. Las métricas detalladas solo se guardan en partidas nuevas.'},
      nl:{statistics:'Statistieken',noSaved:'Nog geen opgeslagen wedstrijden.',overview:'Overzicht',h2h:'Onderling',all:'Alles',week:'Week',month:'Maand',year:'Jaar',avg3:'Gem. / 3 darts',first9:'Eerste 9',checkoutPct:'Checkout %',checkoutPending:'Exacte pogingregistratie volgt',highestCheckout:'Hoogste checkout',scoring:'Scores',performance:'Prestaties',bestLeg:'Beste leg (darts)',avgDartsLeg:'Gem. darts / leg',highestScore:'Hoogste score',winRate:'Winstpercentage',matches:'onderlinge wedstrijden',legs:'Legs',sets:'Sets',last5:'Vorm laatste 5',avgTrend:'AVG-trend',matchHistory:'Onderlinge historie',won:'won',checkout:'Checkout',detailed:({detailed,total})=>`Gedetailleerde statistieken zijn beschikbaar voor ${detailed} van ${total} wedstrijden. Oudere wedstrijden blijven meetellen voor winst.`,older:'Oudere wedstrijden tellen mee voor H2H en winstpercentage. Detailstatistieken worden alleen bij nieuwe wedstrijden opgeslagen.'},
      ru:{statistics:'Статистика',noSaved:'Сохранённых матчей пока нет.',overview:'Обзор',h2h:'Личные встречи',all:'Все',week:'Неделя',month:'Месяц',year:'Год',avg3:'Среднее / 3 дротика',first9:'Первые 9',checkoutPct:'Checkout %',checkoutPending:'Точный учёт попыток будет добавлен',highestCheckout:'Максимальный checkout',scoring:'Наборы',performance:'Результаты',bestLeg:'Лучший лег (дротики)',avgDartsLeg:'Ср. дротиков / лег',highestScore:'Максимальный набор',winRate:'Процент побед',matches:'очных матчей',legs:'Леги',sets:'Сеты',last5:'Форма за 5 матчей',avgTrend:'Тренд среднего',matchHistory:'История личных встреч',won:'победил',checkout:'Checkout',detailed:({detailed,total})=>`Подробная статистика доступна для ${detailed} из ${total} матчей. Старые матчи по-прежнему учитываются в победах.`,older:'Старые матчи учитываются в H2H и проценте побед. Подробные метрики сохраняются только для новых матчей.'},
      zh:{statistics:'统计',noSaved:'暂无已保存的比赛。',overview:'概览',h2h:'对战',all:'全部',week:'一周',month:'一月',year:'一年',avg3:'3镖平均',first9:'前9镖',checkoutPct:'结镖率',checkoutPending:'精确尝试次数统计稍后加入',highestCheckout:'最高结镖',scoring:'得分',performance:'表现',bestLeg:'最佳局（镖数）',avgDartsLeg:'平均镖数 / 局',highestScore:'最高得分',winRate:'胜率',matches:'场对战',legs:'局',sets:'盘',last5:'最近5场状态',avgTrend:'平均分趋势',matchHistory:'对战记录',won:'获胜',checkout:'结镖',detailed:({detailed,total})=>`详细数据适用于 ${detailed}/${total} 场比赛。旧比赛仍计入胜场。`,older:'旧比赛仍计入对战比分和胜率。详细数据仅记录新保存的比赛。'}
    };
    const S=(key,vars)=>{const pack=STATS_I18N[lang]||STATS_I18N.en;const value=pack[key]??STATS_I18N.en[key]??key;return typeof value==='function'?value(vars||{}):value;};"""
s=s.replace(old,new,1)
repl={
"return <div className=\"lobbyCard\"><strong>{L('Statistiky','Statistics')}</strong><div style={{ opacity:.7, marginTop:8 }}>{L('Zatím nejsou odehrané žádné uložené zápasy.','No saved matches yet.')}</div></div>;":"return <div className=\"lobbyCard\"><strong>{S('statistics')}</strong><div style={{ opacity:.7, marginTop:8 }}>{S('noSaved')}</div></div>;",
"{L('Přehled','Overview')}":"{S('overview')}",">Head to Head</button>":">{S('h2h')}</button>",
"<strong style={{ fontSize:18 }}>📊 {L('Statistiky','Statistics')}</strong>":"<strong style={{ fontSize:18 }}>📊 {S('statistics')}</strong>",
"<option value=\"all\">{L('Vše','All')}</option><option value=\"week\">{L('Týden','Week')}</option><option value=\"month\">{L('Měsíc','Month')}</option><option value=\"year\">{L('Rok','Year')}</option>":"<option value=\"all\">{S('all')}</option><option value=\"week\">{S('week')}</option><option value=\"month\">{S('month')}</option><option value=\"year\">{S('year')}</option>",
"{metricCard(fmt(overview.avg3), '3-dart AVG')}":"{metricCard(fmt(overview.avg3), S('avg3'))}","{metricCard(fmt(overview.first9Avg), 'First 9')}":"{metricCard(fmt(overview.first9Avg), S('first9'))}",
"{metricCard(pct(overview.checkoutPct), 'Checkout %', L('Přesná evidence pokusů bude doplněna','Exact attempt tracking pending'))}":"{metricCard(pct(overview.checkoutPct), S('checkoutPct'), S('checkoutPending'))}","{metricCard(overview.highestCheckout ?? '—', L('Nejvyšší checkout','Highest checkout'))}":"{metricCard(overview.highestCheckout ?? '—', S('highestCheckout'))}",
"<strong>{L('Scoring','Scoring')}</strong>":"<strong>{S('scoring')}</strong>","<strong>{L('Výkony','Performance')}</strong>":"<strong>{S('performance')}</strong>","L('Nejlepší leg (šipky)','Best leg (darts)')":"S('bestLeg')","L('Průměr šipek / leg','Avg darts / leg')":"S('avgDartsLeg')","L('Nejvyšší nához','Highest score')":"S('highestScore')","L('Win rate','Win rate')":"S('winRate')",
"{h2hGames.length} {L('vzájemných zápasů','matches')}":"{h2hGames.length} {S('matches')}","<span style={{ opacity:.55 }}>Win rate</span>":"<span style={{ opacity:.55 }}>{S('winRate')}</span>",
"{compareRow(h1.legsWon, 'Legs', h2.legsWon)}":"{compareRow(h1.legsWon, S('legs'), h2.legsWon)}","{compareRow(h1.setsWon, 'Sets', h2.setsWon)}":"{compareRow(h1.setsWon, S('sets'), h2.setsWon)}","{compareRow(fmt(h1.avg3), '3-dart AVG', fmt(h2.avg3))}":"{compareRow(fmt(h1.avg3), S('avg3'), fmt(h2.avg3))}","{compareRow(fmt(h1.first9Avg), 'First 9', fmt(h2.first9Avg))}":"{compareRow(fmt(h1.first9Avg), S('first9'), fmt(h2.first9Avg))}","{compareRow(pct(h1.checkoutPct), 'Checkout %', pct(h2.checkoutPct))}":"{compareRow(pct(h1.checkoutPct), S('checkoutPct'), pct(h2.checkoutPct))}","{compareRow(h1.highestCheckout ?? '—', L('Nejvyšší checkout','Highest checkout'), h2.highestCheckout ?? '—')}":"{compareRow(h1.highestCheckout ?? '—', S('highestCheckout'), h2.highestCheckout ?? '—')}",
"<strong>{L('Forma posledních 5','Last 5 form')}</strong>":"<strong>{S('last5')}</strong>","<strong>{L('Trend AVG','AVG trend')}</strong>":"<strong>{S('avgTrend')}</strong>","<strong>{L('Historie vzájemných zápasů','Match history')}</strong>":"<strong>{S('matchHistory')}</strong>","{L('vyhrál','won')}":"{S('won')}","L('Checkout','Checkout')":"S('checkout')"
}
for a,b in repl.items():
    if a not in s: print('missing',a[:60])
    s=s.replace(a,b)
s=s.replace("{L(`Detailní metriky jsou dostupné u ${overview.detailedMatches} z ${overview.matches} zápasů. Starší zápasy zůstávají započítané do výher.`,`Detailed metrics are available for ${overview.detailedMatches} of ${overview.matches} matches. Older matches still count toward wins.`)}","{S('detailed', { detailed: overview.detailedMatches, total: overview.matches })}")
s=s.replace("{L('Starší zápasy jsou započítané do H2H skóre a win rate. Detailní metriky se plní jen u nově uložených zápasů.','Older matches count toward H2H score and win rate. Detailed metrics populate for newly saved matches.')}","{S('older')}")
p.write_text(s,encoding='utf-8')
